### ISSUE TITLE
MAMP Trouble

### ISSUE THREAD

**Issue by korynorthrop** [davidwinter/wordpress-with-git#4]
This seems like an incredible workflow, however I can't seem to get it to work locally using MAMP. I have a directory called, "Test" in htdocs that has the clone of your repo. After making the necessary edits to wp-config.php (the database settings and default theme) I open "localhost/Test" in a browser, which then spits out the following URL along with a 404 error:

http://localhost/wordpress/wp-admin/install.php

The "Test" directory is missing from the URL. If I type in: http://localhost/Test/wordpress/wp-admin/install.php I am prompted with the expected Wordpress install screen.

Any suggestions on how to get this to recognize the proper directory path? Do I need to change the constant declarations in the wp-config.php file (i.e. WP_SITEURL or WP_HOME)? Do I need to tack on the directory name after $_SERVER['SERVER_NAME'] in those constant definitions?

**Comment by jshakes** [comment]
You'll need to set up a virtual host (vhost) in MAMP's Apache config to set up a local url to that path. In your MAMP vhosts file (usually in /Applications/MAMP/conf/apache.conf or extra/httpd-vhosts.conf) make a vhost entry like this:

<VirtualHost *:80>
DocumentRoot "/path/to/site/root"
ServerName mysite.localhost
</VirtualHost>

Then you'll just need to edit your hosts file to tell your computer to look locally for mysite.localhost. To do this edit /etc/hosts and enter the line:

127.0.0.1 mysite.localhost

Save both, restart MAMP and go to http://mysite.localhost in the browser.

**Comment by davidwinter** [comment]
I think you can set the Apache docroot from the GUI too.

However, if you actually want to have it running from a sub-directory, you'll need to update the `wp-config.php` to:

```
define('WP_SITEURL', 'http://' . $_SERVER['SERVER_NAME'] . '/Test/wordpress');
define('WP_HOME',    'http://' . $_SERVER['SERVER_NAME'] . '/Test');
define('WP_CONTENT_DIR', $_SERVER['DOCUMENT_ROOT'] . '/Test/wp-content');
define('WP_CONTENT_URL', 'http://' . $_SERVER['SERVER_NAME'] . '/Test/wp-content');
```

Give that a try.

**Comment by korynorthrop** [comment]
Thank you for the responses! I'm making some progress here with a few additions of my own. 

```
// Define the local directory making sure to include the :8888/ if those are the ports used by MAMP apache server
$local_dir = ':8888/Test';
$local_content_dir = '/Test';

// If using local development environment prepend $local_dir to paths
if ($_SERVER['SERVER_NAME'] == 'localhost') {
    define('WP_SITEURL', 'http://' . $_SERVER['SERVER_NAME'] . "{$local_dir}/wordpress");
    define('WP_HOME',    'http://' . $_SERVER['SERVER_NAME']) . "{$local_dir}";
    define('WP_CONTENT_DIR', $_SERVER['DOCUMENT_ROOT'] . "{$local_content_dir}/wp-content");
    define('WP_CONTENT_URL', 'http://' . $_SERVER['SERVER_NAME'] . "{$local_dir}/wp-content");
} else {
    // Not local development environment, define constants as normal
    define('WP_SITEURL', 'http://' . $_SERVER['SERVER_NAME'] . '/wordpress');
    define('WP_HOME',    'http://' . $_SERVER['SERVER_NAME']);
    define('WP_CONTENT_DIR', $_SERVER['DOCUMENT_ROOT'] . '/wp-content');
    define('WP_CONTENT_URL', 'http://' . $_SERVER['SERVER_NAME'] . '/wp-content');
}
```

The installation page came up when I went to localhost:8888/Test in my browser (sorry I forgot to include in my original post that my apache port is 8888) and I was able to install Wordpress successfully.

However, from the WP Dashboard, if I click "Visit Site" I am brought to localhost (just "localhost"). I can navigate through other sections of the WP backend just fine, clicking on Pages brings me to the Pages section, clicking Settings brings me to that area. I noticed that the Site Address (URL) field in Settings > General is not what I set in wp-config.php. Site Address (URL) is greyed out and is set to http://localhost.

Any thoughts?

**Comment by korynorthrop** [comment]
I think I figured it out. I seemed to have neglected to move the closing parentheses in the WP_Home definition to the appropriate place at the end of the string.

```
define('WP_HOME',    'http://' . $_SERVER['SERVER_NAME']) . "{$local_dir}";
```

should be:

```
define('WP_HOME',    'http://' . $_SERVER['SERVER_NAME'] . "{$local_dir}");
```

Thanks for your assistance and for your tutorial!
