### ISSUE TITLE
htaccess

### ISSUE THREAD

**Issue by mhulse** [davidwinter/wordpress-with-git#6]
Just out of curiosity, what's your default setup for the `.htaccess` file?

**Comment by davidwinter** [comment]
I currently use nginx, so don't use a `.htaccess` file, however, I would use:

```
DirectoryIndex index.php
FallbackResource index.php
```

**Comment by mhulse** [comment]
> I currently use nginx, so don't use a .htaccess file, however, I would use

Ah, nice. I would prefer that over Apache myself. Thanks for the reply. :octocat:
